"""rename_breakdown_by_category_to_breakdown_by_asset_class

Revision ID: 531cb57f12ed
Revises: cff7bf4c7311
Create Date: 2025-05-30 13:14:32.455961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531cb57f12ed'
down_revision: Union[str, None] = 'cff7bf4c7311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
