"""Add owner management to holdings

Revision ID: cff7bf4c7311
Revises: 001_initial_schema
Create Date: 2025-05-30 11:36:17.438024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cff7bf4c7311'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_class',
               existing_type=postgresql.ENUM('CASHEQ', 'FIXED_INCOME', 'EQUITY', 'REAL_ASSET', 'CRYPTO', name='assetclass'),
               nullable=False)
    op.drop_index('idx_btc_trades_timestamp', table_name='btc_trades')
    op.drop_index('idx_cash_balances_timestamp', table_name='cash_balances')
    op.add_column('holdings', sa.Column('owner_type', sa.Enum('self_', 'spouse', 'child', 'special', name='ownertype'), nullable=False))
    op.add_column('holdings', sa.Column('owner_name', sa.String(length=100), nullable=True))
    op.add_column('holdings', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.drop_index('idx_holdings_asset', table_name='holdings')
    op.drop_index('idx_prices_asset_date', table_name='prices')
    op.drop_index('idx_valuation_snapshots_date_desc', table_name='valuation_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_valuation_snapshots_date_desc', 'valuation_snapshots', [sa.text('date DESC')], unique=False)
    op.create_index('idx_prices_asset_date', 'prices', ['asset_id', sa.text('date DESC')], unique=False)
    op.create_index('idx_holdings_asset', 'holdings', ['asset_id'], unique=False)
    op.drop_column('holdings', 'account_number')
    op.drop_column('holdings', 'owner_name')
    op.drop_column('holdings', 'owner_type')
    op.create_index('idx_cash_balances_timestamp', 'cash_balances', ['institution', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_btc_trades_timestamp', 'btc_trades', [sa.text('timestamp DESC')], unique=False)
    op.alter_column('assets', 'asset_class',
               existing_type=postgresql.ENUM('CASHEQ', 'FIXED_INCOME', 'EQUITY', 'REAL_ASSET', 'CRYPTO', name='assetclass'),
               nullable=True)
    # ### end Alembic commands ###
